const CART_KEY = "salonemarket-cart";
const API_BASE = (document.querySelector('meta[name="xd-api-base"]')?.content || localStorage.getItem("xdmarket_api_base") || "").replace(/\/$/, "");
const $ = selector => document.querySelector(selector);
const escapeHtml = value => String(value ?? "").replace(/[&<>"']/g, char => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[char]);
const money = (amount, currency = "SLE") => currency === "SLE" ? `Le ${new Intl.NumberFormat("en-SL", { maximumFractionDigits: 2 }).format(Number(amount) || 0)}` : new Intl.NumberFormat("en-SL", { style: "currency", currency, maximumFractionDigits: 2 }).format(Number(amount) || 0);
const readCart = () => { try { return JSON.parse(localStorage.getItem(CART_KEY) || "[]"); } catch { return []; } };
const saveCart = cart => { localStorage.setItem(CART_KEY, JSON.stringify(cart)); updateCartBadges(); };
async function api(path, { method = "GET", data } = {}) {
  const response = await fetch(`${API_BASE}${path}`, { method, credentials: "include", headers: method === "GET" ? {} : { "Content-Type": "application/json" }, body: data === undefined ? undefined : JSON.stringify(data) });
  const result = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(result.error || result.message || `Request failed (${response.status}).`);
  return result;
}
function updateCartBadges() {
  const count = readCart().reduce((total, line) => total + Number(line.quantity || 0), 0);
  document.querySelectorAll("[data-cart-count]").forEach(badge => { badge.textContent = count; });
}
function pageHeader(active = "") {
  const links = [["/", "Market"], ["/fashion.html", "Fashion"], ["/electronics.html", "Electronics"], ["/beauty.html", "Beauty"], ["/vendor.html", "Vendor portal"]];
  return `<header class="site-header"><div class="site-header-inner"><a class="site-brand" href="/" aria-label="XD-MARKET home"><img src="/logo.svg" alt=""><span class="site-brand-name">XD-MARKET</span></a><nav class="site-nav" aria-label="Main navigation">${links.map(([href, label]) => `<a href="${href}" ${active === href ? 'aria-current="page"' : ""}>${label}</a>`).join("")}<a href="/cart.html">Cart <span data-cart-count>0</span></a><a class="site-cta" data-auth-link href="/signup.html">Sign in / Join</a><button class="site-signout" data-signout hidden type="button">Sign out</button></nav></div></header><nav class="shop-category-nav"><div class="shop-category-nav-inner"><a href="/">All deals</a><a href="/fashion.html">Fashion & apparel</a><a href="/electronics.html">Electronics & phones</a><a href="/beauty.html">Beauty & care</a><a href="/vendor.html">Sell on XD-MARKET</a></div></nav>`;
}
function pageFooter() {
  return `<footer class="site-footer"><div class="site-footer-inner"><a class="site-brand" href="/"><img src="/logo.svg" alt=""><span class="site-brand-name">XD-MARKET</span></a><nav class="site-footer-links"><a href="/about.html">About</a><a href="/contact.html">Contact</a><a href="/vendor.html">Vendor portal</a><a href="/cart.html">Cart</a></nav><small>First five buyers: free delivery. First ten approved vendors: 5% commission.</small></div></footer>`;
}
function shell({ page, active = "", content }) {
  document.body.classList.add("info-page");
  document.body.innerHTML = `${pageHeader(active)}<main class="shop-content" data-page="${page}">${content}</main>${pageFooter()}`;
  updateCartBadges();
  refreshSessionNav();
}
async function refreshSessionNav() {
  const link=$("[data-auth-link]"),signout=$("[data-signout]");if(!link||!signout)return;
  try{const user=(await api("/api/auth/me")).user;if(user){link.textContent=`Hi, ${user.displayName.split(" ")[0]}`;link.href=user.role==="vendor"?"/vendor.html":user.role==="admin"?"/?admin=1":"/signup.html";signout.hidden=false;signout.onclick=async()=>{try{await api("/api/auth/logout",{method:"POST",data:{}})}finally{localStorage.removeItem("xdmarket_user");location.assign("/")}}}}catch{}
}
async function loadProducts() {
  try { return (await api("/api/store")).products; }
  catch { return []; }
}
function productCard(product) {
  return `<article class="shop-card"><div class="shop-card-image"><img loading="lazy" src="${escapeHtml(product.image || "/logo.svg")}" alt="${escapeHtml(product.title)}"></div><div class="shop-card-body"><small>${escapeHtml(product.vendor || "XD-MARKET seller")} · ${escapeHtml(product.category)}</small><h2>${escapeHtml(product.title)}</h2><div class="shop-card-bottom"><span class="shop-price">${money(product.price, product.currency)}</span><button class="shop-add" type="button" data-add-product="${escapeHtml(product.id)}" aria-label="Add ${escapeHtml(product.title)} to cart">+</button></div></div></article>`;
}
function attachAddButtons(products) {
  document.querySelectorAll("[data-add-product]").forEach(button => button.addEventListener("click", () => {
    const product = products.find(item => item.id === button.dataset.addProduct);
    if (!product) return;
    const cart = readCart();
    const current = cart.length ? products.find(item => item.id === cart[0].productId) : null;
    if (current && current.currency !== product.currency) { alert("Please finish your current cart before adding a different currency."); return; }
    const line = cart.find(item => item.productId === product.id);
    if (line) line.quantity = Math.min(product.stock, line.quantity + 1);
    else cart.push({ productId: product.id, quantity: 1 });
    saveCart(cart);
  }));
}
async function renderCategory(page) {
  const category = { fashion: "Fashion", electronics: "Electronics", beauty: "Beauty" }[page];
  const products = await loadProducts();
  const matches = products.filter(product => product.category.toLowerCase().includes(category.toLowerCase()) || (page === "electronics" && /phone|device|tech/i.test(product.category)) || (page === "beauty" && /health|care|cosmetic/i.test(product.category)));
  shell({ page, active: `/${page}.html`, content: `<section class="shop-page-heading"><div><span class="page-kicker">XD-MARKET categories</span><h1>${category === "Beauty" ? "Beauty & care" : category === "Electronics" ? "Electronics & phones" : "Fashion & apparel"}</h1><p>Discover independent Sierra Leonean sellers and the products they bring to market.</p></div></section><section class="shop-grid">${matches.length ? matches.map(productCard).join("") : `<div class="shop-empty">No ${category.toLowerCase()} listings yet. Browse all deals or check back as local sellers add products.</div>`}</section>` });
  attachAddButtons(matches);
}
async function renderCartPage() {
  const store=await api("/api/store").catch(()=>({products:[],promotions:{freeDeliveryRemaining:0,vendorCommissionRemaining:0}}));
  const products = store.products;
  const cart = readCart();
  const lines = cart.map(line => ({ ...line, product: products.find(product => product.id === line.productId) }));
  const available = lines.filter(line => line.product);
  const subtotal = available.reduce((sum, line) => sum + line.product.price * line.quantity, 0);
  const currency = available[0]?.product.currency || "SLE";
  shell({ page: "cart", active: "/cart.html", content: `<section class="shop-page-heading"><div><span class="page-kicker">Your picks</span><h1>Your shopping cart</h1><p>Review your items before heading to secure checkout.</p></div><a class="page-link-button" href="/">Continue shopping <span>↗</span></a></section><div class="bag-layout"><section id="bag-lines">${available.length ? available.map(line => `<article class="bag-line"><img src="${escapeHtml(line.product.image || "/logo.svg")}" alt=""><div><h2>${escapeHtml(line.product.title)}</h2><small>${escapeHtml(line.product.vendor)} · ${money(line.product.price, line.product.currency)}</small><div class="bag-qty"><button data-quantity="${escapeHtml(line.productId)}" data-step="-1" aria-label="Remove one">−</button><span>${line.quantity}</span><button data-quantity="${escapeHtml(line.productId)}" data-step="1" aria-label="Add one">+</button><button class="bag-remove" data-remove="${escapeHtml(line.productId)}">Remove</button></div></div><strong>${money(line.product.price * line.quantity, line.product.currency)}</strong></article>`).join("") : `<div class="shop-empty">Your cart is empty. Explore the market to find something good.</div>`}</section><aside class="order-summary"><h2>Order summary</h2><div class="promo-message">${store.promotions.freeDeliveryRemaining?`${store.promotions.freeDeliveryRemaining} free-delivery offer${store.promotions.freeDeliveryRemaining===1?"":"s"} remaining for first-time buyers.`:"The first-five free-delivery offer has been claimed."} Delivery is confirmed when you place your order.</div><div class="order-summary-row"><span>Subtotal</span><strong>${money(subtotal, currency)}</strong></div><div class="order-summary-row"><span>Delivery</span><span>Confirmed at checkout</span></div><div class="order-summary-row order-summary-total"><span>Total</span><strong>${money(subtotal, currency)}</strong></div>${available.length ? `<a class="page-link-button" style="width:100%" href="/checkout.html">Continue to checkout <span>↗</span></a>` : ""}</aside></div>` });
  document.querySelectorAll("[data-quantity]").forEach(button => button.addEventListener("click", () => { const lines = readCart(), line = lines.find(item => item.productId === button.dataset.quantity), product = products.find(item => item.id === button.dataset.quantity); if (!line) return; line.quantity += Number(button.dataset.step); if (line.quantity < 1) lines.splice(lines.indexOf(line), 1); else if (product) line.quantity = Math.min(line.quantity, product.stock); saveCart(lines); renderCartPage(); }));
  document.querySelectorAll("[data-remove]").forEach(button => button.addEventListener("click", () => { saveCart(readCart().filter(line => line.productId !== button.dataset.remove)); renderCartPage(); }));
}
async function renderSignup() {
  const params = new URLSearchParams(location.search), mode = params.get("mode") === "login" ? "login" : "register", next = params.get("next") === "checkout" ? "/checkout.html" : "", defaultRole=params.get("role")==="vendor"?"vendor":"buyer";
  shell({ page: "signup", content: `<section class="shop-page-heading"><div><span class="page-kicker">Join the market</span><h1>${mode === "login" ? "Welcome back." : "Create your XD-MARKET account."}</h1><p>One secure sign-in for shopping and selling.</p></div></section><div class="story-grid"><form class="shop-form" id="auth-form"><div class="shop-form-grid">${mode === "register" ? `<div class="shop-field full"><label for="signup-name">Full name</label><input id="signup-name" name="displayName" autocomplete="name" maxlength="100" required></div><div class="shop-field full"><label for="signup-phone">Phone number</label><input id="signup-phone" name="phone" type="tel" autocomplete="tel" placeholder="+232 76 123 456" required></div>` : ""}<div class="shop-field full"><label for="signup-email">Email address</label><input id="signup-email" name="email" type="email" autocomplete="email" maxlength="254" required></div>${mode === "register" ? `<div class="shop-field full"><label for="signup-role">Account type</label><select id="signup-role" name="role"><option value="buyer">Buyer / shopper</option><option value="vendor">Vendor / seller</option></select></div><div class="shop-field full" id="store-name-field" hidden><label for="signup-store">Shop name</label><input id="signup-store" name="storeName" maxlength="100"></div>` : ""}<div class="shop-field full"><label for="signup-password">Password ${mode === "register" ? "(12 characters minimum)" : ""}</label><input id="signup-password" name="password" type="password" minlength="${mode === "register" ? 12 : 1}" maxlength="128" autocomplete="${mode === "register" ? "new-password" : "current-password"}" required></div></div><button class="page-link-button" type="submit">${mode === "login" ? "Sign in" : "Create account"} <span>↗</span></button><p class="shop-alert" id="auth-status" aria-live="polite"></p><p><a href="/signup.html?mode=${mode === "login" ? "register" : "login"}${next ? "&next=checkout" : ""}">${mode === "login" ? "Create an account" : "Already registered? Sign in"}</a></p></form><aside class="contact-aside"><span class="page-kicker">For new sellers</span><h2>Join the first ten vendor partners.</h2><p>The first ten vendors approved by an administrator receive a 5% platform commission rate. All other stores use the active admin-configured rate.</p><p>Vendor accounts need approval before products can be listed. Passwords are hashed server-side; sign-in uses a secure, HttpOnly session cookie.</p></aside></div>` });
  const roleSelect = $("#signup-role");
  roleSelect?.addEventListener("change", () => { const isVendor = roleSelect.value === "vendor"; $("#store-name-field").hidden = !isVendor; $("#signup-store").required = isVendor; });
  if(roleSelect){roleSelect.value=defaultRole;roleSelect.dispatchEvent(new Event("change"));}
  $("#auth-form").addEventListener("submit", async event => {
    event.preventDefault(); const status = $("#auth-status"), button = event.currentTarget.querySelector("button[type=submit]"); button.disabled = true; status.textContent = "";
    try {
      const data = Object.fromEntries(new FormData(event.currentTarget));
      const result = await api(mode === "login" ? "/api/auth/login" : "/api/auth/register", { method: "POST", data });
      localStorage.setItem("xdmarket_user", JSON.stringify({ id: result.user.id, displayName: result.user.displayName, role: result.user.role, status: result.user.status }));
      location.href = next || (result.user.role === "vendor" ? "/vendor.html" : "/");
    } catch (error) { status.textContent = error.message; button.disabled = false; }
  });
}
async function renderCheckout() {
  const products = await loadProducts(), cart = readCart(), lines = cart.map(line => ({ ...line, product: products.find(product => product.id === line.productId) })).filter(line => line.product);
  if (!lines.length) { location.replace("/cart.html"); return; }
  let currentUser = null; try { currentUser = (await api("/api/auth/me")).user; } catch {}
  if (!currentUser) { shell({ page: "checkout", active: "/cart.html", content: `<section class="shop-page-heading"><div><span class="page-kicker">Secure checkout</span><h1>Sign in to continue.</h1><p>Your order and payment details are handled by XD-MARKET’s secure server.</p></div></section><a class="page-link-button" href="/signup.html?mode=login&next=checkout">Sign in or create an account <span>↗</span></a>` }); return; }
  const subtotal = lines.reduce((sum, line) => sum + line.product.price * line.quantity, 0), currency = lines[0].product.currency;
  shell({ page: "checkout", active: "/cart.html", content: `<section class="shop-page-heading"><div><span class="page-kicker">Secure checkout</span><h1>Delivery and payment.</h1><p>Choose how to pay. Mobile money, cards, and bank transfers open through Flutterwave.</p></div></section><div class="checkout-layout"><form id="checkout-form" class="shop-form"><div class="shop-form-grid"><div class="shop-field"><label for="buyer-name">Full name</label><input id="buyer-name" name="name" value="${escapeHtml(currentUser.displayName)}" required></div><div class="shop-field"><label for="buyer-email">Email address</label><input id="buyer-email" name="email" type="email" value="${escapeHtml(currentUser.email)}" required></div><div class="shop-field"><label for="buyer-phone">Phone number</label><input id="buyer-phone" name="phone" type="tel" value="${escapeHtml(currentUser.phone || "")}" placeholder="+232" required></div><div class="shop-field"><label for="buyer-city">City or district</label><input id="buyer-city" name="city" placeholder="Freetown" required></div><div class="shop-field full"><label for="buyer-address">Delivery address</label><input id="buyer-address" name="address" autocomplete="street-address" required></div><div class="shop-field full"><label>Payment method</label><div class="shop-radio-grid"><label class="shop-radio"><input type="radio" name="paymentMethod" value="orange_money" checked> Orange Money</label><label class="shop-radio"><input type="radio" name="paymentMethod" value="afrimoney"> Afrimoney</label><label class="shop-radio"><input type="radio" name="paymentMethod" value="card"> Visa / Mastercard</label><label class="shop-radio"><input type="radio" name="paymentMethod" value="bank_transfer"> Bank transfer</label><label class="shop-radio"><input type="radio" name="paymentMethod" value="cash_on_delivery"> Cash on delivery</label></div></div></div><button class="page-link-button" type="submit">Place order <span>↗</span></button><p id="checkout-status" class="shop-alert" aria-live="polite"></p></form><aside class="order-summary"><h2>Your order</h2>${lines.map(line => `<div class="order-summary-row"><span>${escapeHtml(line.product.title)} × ${line.quantity}</span><strong>${money(line.product.price * line.quantity, currency)}</strong></div>`).join("")}<div class="order-summary-row"><span>Subtotal</span><strong>${money(subtotal, currency)}</strong></div><div class="order-summary-row"><span>Delivery</span><span>Confirmed after order</span></div><div class="promo-message">First five buyers can receive free delivery. The server confirms availability when this order is placed.</div><div class="order-summary-row order-summary-total"><span>Items total</span><strong>${money(subtotal, currency)}</strong></div></aside></div>` });
  $("#checkout-form").addEventListener("submit", async event => {
    event.preventDefault(); const button=event.currentTarget.querySelector("button[type=submit]"),status=$("#checkout-status");button.disabled=true;status.textContent="Placing your order…";
    try { const data=Object.fromEntries(new FormData(event.currentTarget));data.items=cart;const result=await api("/api/orders",{method:"POST",data});if(result.checkoutUrl){location.assign(result.checkoutUrl);return}saveCart([]);shell({page:"checkout",content:`<section class="page-hero"><span class="page-kicker">Order received</span><h1>${result.order.freeDelivery?"You’re one of the first five!":"Your order is on its way."}</h1><p>${result.order.freeDelivery?"Free delivery has been applied to this order.":"The seller will contact you about delivery."}</p><p>Order reference: ${escapeHtml(result.order.id)}</p><a class="page-link-button" href="/">Back to the market <span>↗</span></a></section>`});}
    catch(error){status.textContent=error.message;button.disabled=false;}
  });
}
async function renderVendorPortal() {
  let user=null;try{user=(await api("/api/auth/me")).user}catch{}
  if(!user||user.role!=="vendor") { shell({page:"vendor",active:"/vendor.html",content:`<section class="shop-page-heading"><div><span class="page-kicker">XD-MARKET vendor portal</span><h1>Grow your shop.</h1><p>Apply to sell, reach customers in Sierra Leone and beyond, and manage orders from one vendor portal.</p></div></section><section class="steps"><article class="step"><span class="step-number">01</span><h2>Apply for approval</h2><p>Create a vendor account. The marketplace admin reviews each application before the account can list products.</p></article><article class="step"><span class="step-number">02</span><h2>List your products</h2><p>Add a product photo, description, category, stock, and SLE or USD price. Earnings are calculated before a listing is published.</p></article><article class="step"><span class="step-number">03</span><h2>Fulfil and request payout</h2><p>Review shipping details, update orders, track your balance, and request a payout to Orange Money, Afrimoney, or a bank account.</p></article></section><section class="vendor-callout"><h2>First ten approved vendors pay 5% commission.</h2><p>After the introductory slots, the standard commission is set by the marketplace admin between 5% and 10%.</p><a class="page-link-button" href="/signup.html?role=vendor">Apply to sell <span>↗</span></a><p><a href="/signup.html?mode=login">Already have a vendor account? Sign in</a></p></section>`});return;}
  if(user.status!=="approved"){shell({page:"vendor",active:"/vendor.html",content:`<section class="page-hero"><span class="page-kicker">Vendor application</span><h1>Thanks, ${escapeHtml(user.displayName)}.</h1><p>Your shop is waiting for admin approval. You can return here after it has been reviewed.</p><a class="page-link-button" href="/">Back to the market</a></section>`});return;}
  let data;try{data=await api("/api/vendor/summary")}catch(error){shell({page:"vendor",active:"/vendor.html",content:`<p class="shop-alert">${escapeHtml(error.message)}</p>`});return;}
  const tab=new URLSearchParams(location.search).get("tab")||"overview";
  shell({page:"vendor",active:"/vendor.html",content:`<section class="shop-page-heading"><div><span class="page-kicker">Vendor portal</span><h1>${escapeHtml(user.storeName)}</h1><p>Commission rate: ${data.commissionPercent}% ${data.promoRate?"· first-ten vendor offer applied":""}</p></div><a class="page-link-button" href="/">Back to market</a></section><nav class="shop-dashboard-tabs"><a class="${tab==="overview"?"active":""}" href="/vendor.html?tab=overview">Overview</a><a class="${tab==="products"?"active":""}" href="/vendor.html?tab=products">Products</a><a class="${tab==="orders"?"active":""}" href="/vendor.html?tab=orders">Orders</a><a class="${tab==="payouts"?"active":""}" href="/vendor.html?tab=payouts">Balance & payouts</a></nav><div class="shop-dashboard-content" id="vendor-content"></div>`});
  const mount=$("#vendor-content"),currencies=Object.keys(data.balances); 
  if(tab==="products") mount.innerHTML=`<form id="vendor-product-form" class="shop-form"><h2>Add a product</h2><div class="shop-form-grid"><div class="shop-field full"><label>Product name</label><input name="title" required maxlength="100"></div><div class="shop-field full"><label>Description</label><textarea name="description" required maxlength="1500"></textarea></div><div class="shop-field"><label>Category</label><select name="category"><option>Fashion</option><option>Electronics</option><option>Beauty</option><option>Handmade</option><option>Food</option><option>Home</option></select></div><div class="shop-field"><label>Price</label><input name="price" type="number" min="0.01" step="0.01" required></div><div class="shop-field"><label>Currency</label><select name="currency"><option value="SLE">SLE · Le</option><option value="USD">USD · $</option></select></div><div class="shop-field"><label>Stock quantity</label><input name="stock" type="number" min="0" step="1" required></div><div class="shop-field full"><label>Product photo</label><input name="photo" type="file" accept="image/png,image/jpeg,image/webp"></div></div><p class="promo-message" id="vendor-earnings">Enter your price to see your net earnings.</p><button class="page-link-button">Publish product</button><p class="shop-alert" id="vendor-product-status"></p></form><section class="page-section"><h2>Your listings</h2>${data.products.length?`<div class="shop-grid">${data.products.map(productCard).join("")}</div>`:`<p>You have no products listed yet.</p>`}</section>`;
  else if(tab==="orders") mount.innerHTML=`<h2>Your orders</h2>${data.orders.length?`<div class="table-wrap"><table class="data-table"><thead><tr><th>Order</th><th>Customer / delivery</th><th>Items</th><th>Payment</th><th>Fulfilment</th></tr></thead><tbody>${data.orders.map(order=>`<tr><td>${escapeHtml(order.id.slice(0,8))}</td><td>${escapeHtml(order.customerName)}<br>${escapeHtml(order.phone)}<br>${escapeHtml(order.address)}, ${escapeHtml(order.city)}</td><td>${order.items.map(item=>`${escapeHtml(item.title)} × ${item.quantity}`).join("<br>")}</td><td>${escapeHtml(order.paymentStatus)}</td><td><select data-update-order="${escapeHtml(order.id)}"><option value="">${escapeHtml(order.status)}</option><option value="processing">Processing</option><option value="shipped">Shipped</option><option value="delivered">Delivered</option></select></td></tr>`).join("")}</tbody></table></div>`:`<p>No orders yet.</p>`}`;
  else if(tab==="payouts") mount.innerHTML=`<div class="stats-grid">${currencies.map(currency=>`<article class="stat"><small>Available ${currency}</small><strong>${money(data.balances[currency],currency)}</strong></article>`).join("")||`<article class="stat"><small>Available SLE</small><strong>Le 0</strong></article>`}<article class="stat"><small>Commission</small><strong>${data.commissionPercent}%</strong></article></div><div class="story-grid"><form id="payout-request" class="shop-form"><h2>Request a payout</h2><div class="shop-form-grid"><div class="shop-field"><label>Amount</label><input name="amount" type="number" min="0.01" step="0.01" required></div><div class="shop-field"><label>Currency</label><select name="currency">${(currencies.length?currencies:["SLE"]).map(currency=>`<option>${currency}</option>`).join("")}</select></div><div class="shop-field"><label>Payout method</label><select name="method"><option value="orange_money">Orange Money</option><option value="afrimoney">Afrimoney</option><option value="bank_transfer">Bank transfer</option></select></div><div class="shop-field"><label>Wallet or bank details</label><input name="destination" required></div></div><button class="page-link-button">Submit payout request</button><p id="payout-status" class="shop-alert"></p></form><section><h2>Recent requests</h2>${data.payouts.map(payout=>`<p>${money(payout.amount,payout.currency)} · ${escapeHtml(payout.method)} · ${escapeHtml(payout.status)}</p>`).join("")||"<p>No payout requests yet.</p>"}</section></div>`;
  else mount.innerHTML=`<div class="stats-grid"><article class="stat"><small>Available balance</small><strong>${currencies.map(currency=>money(data.balances[currency],currency)).join(" · ")||"Le 0"}</strong></article><article class="stat"><small>Completed gross sales</small><strong>${data.orders.filter(order=>order.paymentStatus==="paid").map(order=>money(order.gross,order.currency)).join(" · ")||"Le 0"}</strong></article><article class="stat"><small>Platform commission</small><strong>${data.commissionPercent}%</strong></article><article class="stat"><small>Listings / orders</small><strong>${data.products.length} / ${data.orders.length}</strong></article></div><div class="shop-grid">${data.products.slice(0,4).map(productCard).join("")}</div>`;
  $("#vendor-product-form")?.addEventListener("input",()=>{const fields=new FormData($("#vendor-product-form")),price=Number(fields.get("price"));$("#vendor-earnings").textContent=price>0?`Price: ${money(price,fields.get("currency"))} · your earnings after ${data.commissionPercent}% commission: ${money(price*(1-data.commissionPercent/100),fields.get("currency"))}`:"Enter your price to see your net earnings."});
  $("#vendor-product-form")?.addEventListener("submit",async event=>{event.preventDefault();const form=event.currentTarget,fields=new FormData(form),file=fields.get("photo"),status=$("#vendor-product-status");try{let image="";if(file?.size){if(file.size>2*1024*1024)throw new Error("Choose an image smaller than 2 MB.");image=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file)})}const data=Object.fromEntries(fields);delete data.photo;data.image=image;await api("/api/vendor/products",{method:"POST",data});location.reload()}catch(error){status.textContent=error.message}});
  $("#payout-request")?.addEventListener("submit",async event=>{event.preventDefault();try{await api("/api/vendor/payouts",{method:"POST",data:Object.fromEntries(new FormData(event.currentTarget))});location.reload()}catch(error){$("#payout-status").textContent=error.message}});
  document.querySelectorAll("[data-update-order]").forEach(select=>select.addEventListener("change",async()=>{if(!select.value)return;try{await api(`/api/vendor/orders/${select.dataset.updateOrder}`,{method:"PATCH",data:{status:select.value}});location.reload()}catch(error){alert(error.message)}}));
}
async function init() {
  updateCartBadges();
  const page=document.body.dataset.page;
  if(page==="fashion"||page==="electronics"||page==="beauty") await renderCategory(page);
  else if(page==="cart") await renderCartPage();
  else if(page==="checkout") await renderCheckout();
  else if(page==="signup") await renderSignup();
  else if(page==="vendor") await renderVendorPortal();
}
init().catch(error=>{const main=$("main");if(main)main.innerHTML=`<p class="shop-alert">${escapeHtml(error.message)}</p>`;});
